//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReBirth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int sessionID { get; set; }
        public int patientID { get; set; }
        public int specialistID { get; set; }
        public Nullable<int> excerciseID { get; set; }
    
        public virtual Exercis Exercis { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
